import re
import pprint
from elftools.elf.elffile import ELFFile
def list_dynsym(elf, filters):
    with open(elf, 'rb') as f:
        elf = ELFFile(f)

        symbol_names = []
        
        # Find the .dynsym section
        dynsym_section = elf.get_section_by_name('.dynsym')
        if not dynsym_section:
            return
        
        for symbol in dynsym_section.iter_symbols():
            #code.interact(local=locals())
            if symbol['st_info']['type'] != 'STT_FUNC':
                continue

            if any(x in symbol.name for x in filters): 
                if 'OBJECT' not in symbol.name:
                    symbol_names.append(symbol.name)
        return symbol_names
        

#openssl_filters = ["RSA", "EC", "DSA", "DH"]

#openssl_APIs = list_dynsym("/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1", openssl_filters)
openssl11_APIs = ['DH_security_bits', 'i2d_RSAPublicKey', 'PEM_read_RSAPublicKey', 'ECDSA_SIG_free', 'DH_new_method', 'd2i_RSAPublicKey_bio', 'ASN1_UNIVERSALSTRING_to_string', 'PEM_write_RSA_PUBKEY', 
                'EC_KEY_OpenSSL', 'RSA_print', 'RSA_padding_check_PKCS1_OAEP_mgf1', 'DSA_get0_priv_key', 'RSA_bits', 'RSA_clear_flags', 'DSA_verify', 'ENGINE_get_default_DSA', 'i2d_RSAPublicKey_bio', 
                'DH_get0_g', 'DHparams_print_fp', 'd2i_RSAPublicKey', 'DH_get0_p', 'DH_get0_q', 'd2i_DSA_PUBKEY_fp', 'RSA_meth_set_priv_enc', 'RSA_flags', 'i2o_ECPublicKey', 'EC_GROUP_get0_cofactor', 
                'EC_POINT_copy', 'EC_POINT_free', 'i2d_RSAPrivateKey', 'EC_KEY_METHOD_get_verify', 'EC_GROUP_set_generator', 'RSA_meth_get_priv_enc', 'RSA_meth_set1_name', 'EC_POINT_dup', 'DH_get_1024_160', 
                'RSA_padding_add_PKCS1_PSS', 'DSAparams_print_fp', 'DH_check_params_ex', 'DSA_test_flags', 'd2i_RSAPublicKey_fp', 'EC_GROUP_set_point_conversion_form', 'EC_KEY_key2buf', 'RSA_verify_PKCS1_PSS_mgf1', 
                'DH_compute_key_padded', 'DH_get_default_method', 'd2i_EC_PUBKEY_bio', 'PEM_write_bio_RSAPrivateKey', 'EC_POINT_bn2point', 'EC_KEY_oct2priv', 'DH_set_default_method', 'DSA_get0_key', 'RSA_test_flags', 
                'DHparams_print', 'PKCS7_RECIP_INFO_get0_alg', 'EC_KEY_get0_private_key', 'DSA_meth_get_flags', 'ENGINE_set_default_DSA', 'EC_GFp_nistp256_method', 'DSA_meth_set_sign', 'EC_GROUP_set_asn1_flag', 
                'RSA_size', 'RSA_X931_generate_key_ex', 'PEM_read_DSA_PUBKEY', 'DH_OpenSSL', 'EC_POINT_point2hex', 'DSA_generate_parameters', 'ENGINE_set_RSA', 'EC_POINT_add', 'ECPKPARAMETERS_free', 'EVP_PKEY_get0_DSA', 
                'PEM_read_bio_DHparams', 'RSA_meth_set_sign', 'EC_POINT_oct2point', 'i2d_DSAPrivateKey', 'RSA_set0_key', 'i2d_RSAPublicKey_fp', 'DSA_do_sign', 'PKCS7_RECIP_INFO_new', 'EC_GROUP_precompute_mult', 'DH_meth_set_generate_key', 
                'RSA_get0_multi_prime_crt_params', 'RSA_meth_get_verify', 'RSA_generate_key_ex', 'EC_POINT_set_Jprojective_coordinates_GFp', 'DH_test_flags', 'DSA_meth_set0_app_data', 'DSA_get0_g', 'DH_meth_set_init', 'DSA_get0_p', 'DSA_get0_q', 
                'DH_get_2048_224', 'DH_meth_new', 'EVP_PKEY_get1_RSA', 'DSA_new', 'EC_POINT_is_on_curve', 'DH_check_params', 'DSA_meth_set_verify', 'DSA_meth_set_bn_mod_exp', 'DH_free', 'EC_POINT_set_compressed_coordinates_GFp', 'RSA_up_ref', 
                'EC_KEY_up_ref', 'd2i_ECParameters', 'DH_get_2048_256', 'RSA_meth_set_finish', 'RSA_get_multi_prime_extra_count', 'EC_GROUP_new', 'PEM_write_DSA_PUBKEY', 'd2i_PKCS7_RECIP_INFO', 'EC_GROUP_get_point_conversion_form', 
                'PEM_read_bio_DSAparams', 'RSA_padding_check_X931', 'ECDSA_sign_ex', 'RSAPublicKey_dup', 'PEM_write_ECPrivateKey', 'EC_curve_nist2nid', 'EC_KEY_oct2key', 'i2d_PKCS7_RECIP_INFO', 'DSA_set_method', 'RSA_meth_get_multi_prime_keygen', 
                'DH_set_flags', 'DH_generate_key', 'BN_RECP_CTX_set', 'd2i_DSA_SIG', 'EC_KEY_set_method', 'DH_check_pub_key_ex', 'RSA_padding_add_PKCS1_type_1', 'RSA_padding_add_PKCS1_type_2', 'EC_KEY_print', 'EC_GROUP_get_mont_data', 'i2d_DSAPrivateKey_bio', 
                'PEM_read_ECPKParameters', 'd2i_RSA_PUBKEY', 'DSA_meth_get_mod_exp', 'PEM_read_EC_PUBKEY', 'RSA_meth_get_pub_dec', 'RSA_PSS_PARAMS_free', 'RSA_meth_set_bn_mod_exp', 'EC_GROUP_get_pentanomial_basis', 'EC_KEY_get_conv_form', 'DSA_get_ex_data', 
                'EC_KEY_priv2buf', 'DSA_meth_get_finish', 'EC_GFp_simple_method', 'i2d_RSAPrivateKey_bio', 'DH_get0_pub_key', 'EC_KEY_METHOD_get_sign', 'EC_GF2m_simple_method', 'i2d_RSA_PSS_PARAMS', 'EC_KEY_get_enc_flags', 'DSAparams_dup', 
                'EC_POINT_set_compressed_coordinates_GF2m', 'd2i_DSAPrivateKey_fp', 'EC_GROUP_get_order', 'o2i_ECPublicKey', 'EC_GROUP_get_basis_type', 'DSA_generate_key', 'DH_meth_get0_name', 'EC_KEY_generate_key', 'ECDSA_sign_setup', 'PEM_read_bio_EC_PUBKEY', 
                'DSA_meth_new', 'ASN1_UNIVERSALSTRING_new', 'DSA_meth_set_mod_exp', 'RSA_meth_set_pub_dec', 'RSA_padding_add_PKCS1_OAEP', 'PEM_write_RSAPublicKey', 'i2d_DSA_PUBKEY', 'DSA_set_ex_data', 'DSA_set_default_method', 'ECPARAMETERS_new', 
                'EC_POINT_set_affine_coordinates_GFp', 'EC_KEY_check_key', 'DH_meth_get_generate_params', 'DSA_meth_get0_name', 'DSA_get0_pub_key', 'RSA_public_encrypt', 'DHparams_dup', 'DH_meth_get0_app_data', 'EC_GROUP_copy', 'EC_GROUP_cmp', 'EC_GROUP_free', 
                'EC_get_builtin_curves', 'DSA_meth_get_init', 'EC_KEY_METHOD_set_keygen', 'RSA_meth_get_flags', 'EC_GROUP_get_degree', 'DH_meth_set1_name', 'PEM_write_EC_PUBKEY', 'EC_KEY_get0_public_key', 'RSA_meth_set0_app_data', 'EC_POINT_set_affine_coordinates_GF2m', 
                'PEM_read_RSAPrivateKey', 'EC_POINT_hex2point', 'EC_KEY_METHOD_free', 'ECDSA_do_verify', 'DH_get0_engine', 'EC_GROUP_new_from_ecparameters', 'RSA_meth_dup', 'DSA_SIG_get0', 'd2i_ECPrivateKey_bio', 'ECDSA_sign', 'EC_GROUP_new_from_ecpkparameters', 
                'RSA_free', 'RSA_meth_get_init', 'ENGINE_register_all_DH', 'EC_POINT_clear_free', 'ENGINE_register_all_EC', 'EC_KEY_new', 'DH_set_length', 'RSA_public_decrypt', 'ERR_load_DH_strings', 'ENGINE_set_DH', 'i2d_EC_PUBKEY_fp', 'DSA_meth_set_paramgen', 
                'ECDSA_do_sign_ex', 'i2d_ECPrivateKey_bio', 'EC_METHOD_get_field_type', 'EVP_PKEY_set1_EC_KEY', 'PEM_write_bio_ECPrivateKey', 'd2i_DHxparams', 'ENGINE_set_EC', 'RSA_get0_multi_prime_factors', 'RSA_private_decrypt', 'EC_KEY_METHOD_set_init', 
                'd2i_RSA_PUBKEY_fp', 'DH_get0_pqg', 'RSA_new', 'ENGINE_register_all_RSA', 'i2d_DSAPublicKey', 'd2i_RSA_PSS_PARAMS', 'EC_GROUP_check_discriminant', 'ENGINE_get_default_DH', 'ECParameters_print', 'DSA_meth_get_paramgen', 'DH_get0_priv_key', 
                'ENGINE_set_DSA', 'ENGINE_get_RSA', 'RSA_verify', 'ENGINE_get_default_EC', 'EVP_PKEY_get0_EC_KEY', 'DH_set0_key', 'EC_GROUP_clear_free', 'EC_KEY_get0_group', 'DH_clear_flags', 'ECDSA_SIG_get0', 'EC_POINT_set_to_infinity', 'EC_GROUP_get_curve_name', 
                'DH_generate_parameters', 'DSAparams_print', 'EC_KEY_set_conv_form', 'PEM_write_bio_DHparams', 'EC_KEY_print_fp', 'PEM_read_DSAPrivateKey', 'PEM_read_bio_DSA_PUBKEY', 'RSA_meth_set_keygen', 'RSA_padding_check_PKCS1_type_1', 'RSA_padding_check_PKCS1_type_2', 
                'EVP_PKEY_get1_DSA', 'EC_POINT_mul', 'DH_meth_set_compute_key', 'DH_meth_get_generate_key', 'DIRECTORYSTRING_free', 'DH_meth_set_generate_params', 'ENGINE_set_default_DH', 'RSA_X931_derive_ex', 'DH_get_length', 'EC_GROUP_set_curve_GFp', 'ENGINE_set_default_EC', 
                'DSA_SIG_new', 'PKCS7_RECIP_INFO_set', 'i2d_ECPrivateKey', 'PEM_write_ECPKParameters', 'd2i_DSAparams', 'PEM_write_bio_RSA_PUBKEY', 'd2i_RSAPrivateKey', 'ECPARAMETERS_free', 'EC_GROUP_get_seed_len', 'RSA_padding_add_PKCS1_OAEP_mgf1', 'EC_GROUP_set_curve_name', 
                'd2i_DHparams', 'EC_POINT_method_of', 'PEM_read_RSA_PUBKEY', 'RSA_meth_get_mod_exp', 'DH_meth_set0_app_data', 'RSA_set_default_method', 'ERR_load_RSA_strings', 'EC_GFp_nistp521_method', 'EC_GROUP_get_asn1_flag', 'EC_GROUP_get0_seed', 'ECDSA_size', 
                'RSA_sign_ASN1_OCTET_STRING', 'd2i_ASN1_UNIVERSALSTRING', 'DSA_get0_pqg', 'd2i_RSAPrivateKey_fp', 'i2d_RSA_PUBKEY_fp', 'DSA_meth_get_keygen', 'ECDSA_SIG_new', 'RSA_generate_key', 'EC_KEY_precompute_mult', 'i2d_RSA_OAEP_PARAMS', 'EC_KEY_METHOD_set_verify', 
                'EC_POINT_point2bn', 'RSA_get0_crt_params', 'EC_GROUP_get_trinomial_basis', 'RSA_padding_add_none', 'RSA_set_flags', 'EVP_PKEY_get1_DH', 'i2d_RSAPrivateKey_fp', 'EC_GROUP_new_by_curve_name', 'DSA_set0_key', 'RSA_get0_d', 'RSA_get0_e', 'RSA_get_ex_data', 
                'RSA_meth_set_mod_exp', 'EC_GROUP_order_bits', 'DSA_sign', 'RSA_get0_n', 'RSA_get0_p', 'RSA_get0_q', 'i2d_DHxparams', 'DSA_meth_get_bn_mod_exp', 'EC_KEY_set_default_method', 'i2d_ECPKParameters', 'EC_GROUP_set_curve', 'RSA_null_method', 'DSA_meth_get0_app_data', 
                'RSA_verify_PKCS1_PSS', 'RSA_set0_factors', 'EC_KEY_set_private_key', 'EC_POINT_invert', 'd2i_EC_PUBKEY', 'RSA_meth_get0_name', 'PKCS7_RECIP_INFO_free', 'DSA_SIG_set0', 'd2i_DSAPrivateKey', 'EC_KEY_METHOD_get_compute_key', 'EC_KEY_can_sign', 'DH_meth_set_flags', 
                'EC_KEY_priv2oct', 'RSA_get0_factors', 'RSA_set_ex_data', 'RSA_get_version', 'RSA_print_fp', 'RSA_meth_get_pub_enc', 'PEM_write_bio_DHxparams', 'EC_GROUP_check', 'EC_KEY_set_asn1_flag', 'EC_POINT_new', 'ENGINE_register_RSA', 'EC_GROUP_get_cofactor', 'EC_GROUP_get_curve', 
                'RSA_set0_crt_params', 'i2d_DSA_PUBKEY_fp', 'DSA_bits', 'i2d_DSA_SIG', 'i2d_DHparams', 'EVP_PKEY_set1_RSA', 'DSA_set_flags', 'DSA_meth_set_flags', 'DSA_security_bits', 'PEM_read_bio_ECPrivateKey', 'RSA_meth_set_multi_prime_keygen', 'DH_get_nid', 'RSA_meth_set_verify', 
                'RSA_meth_free', 'ECDH_compute_key', 'DH_meth_get_flags', 'RSA_meth_get_bn_mod_exp', 'ECDSA_SIG_set0', 'RSA_meth_set_pub_enc', 'DH_meth_dup', 'i2d_DSAparams', 'RSA_security_bits', 'ENGINE_unregister_RSA', 'EC_KEY_METHOD_new', 'i2d_EC_PUBKEY_bio', 'i2d_ASN1_UNIVERSALSTRING', 
                'EC_KEY_METHOD_set_compute_key', 'EC_POINT_point2buf', 'RSA_get0_iqmp', 'RSAPrivateKey_dup', 'EC_GROUP_dup', 'ENGINE_unregister_DH', 'DSA_meth_get_sign', 'DH_check_ex', 'DH_up_ref', 'PEM_write_bio_DSA_PUBKEY', 'ECPKParameters_print_fp', 'EC_GFp_nistp224_method', 'ENGINE_unregister_EC', 
                'd2i_ECPKParameters', 'ENGINE_register_all_DSA', 'EC_KEY_set_group', 'EC_GROUP_method_of', 'RSA_X931_hash_id', 'EC_POINT_get_Jprojective_coordinates_GFp', 'RSA_set0_multi_prime_params', 'i2d_RSA_PUBKEY', 'EVP_PKEY_set1_DH', 'RSA_set_method', 'PEM_write_bio_DSAparams', 'ENGINE_get_DSA', 
                'EC_POINT_set_compressed_coordinates', 'RSA_meth_get_sign', 'DSA_size', 'DSA_get0_engine', 'RSA_get0_key', 'RSA_meth_set_priv_dec', 'DSA_meth_get_verify', 'PEM_read_bio_RSAPublicKey', 'PEM_read_bio_ECPKParameters', 'i2d_ECParameters', 'EC_GROUP_have_precompute_mult', 'DSA_meth_free', 
                'ECDSA_SIG_get0_r', 'ECDSA_SIG_get0_s', 'EC_KEY_set_public_key', 'EC_KEY_METHOD_set_sign', 'ERR_load_EC_strings', 'ASN1_UNIVERSALSTRING_free', 'DH_meth_get_init', 'RSA_meth_get_priv_dec', 'RSA_meth_get_finish', 'i2d_EC_PUBKEY', 'EC_curve_nid2nist', 'EC_POINT_set_affine_coordinates', 
                'DH_generate_parameters_ex', 'PEM_write_DHxparams', 'PEM_write_bio_DSAPrivateKey', 'EC_POINT_get_affine_coordinates_GFp', 'PEM_read_DSAparams', 'EC_POINT_cmp', 'RSA_setup_blinding', 'DSA_meth_set_finish', 'i2d_DSAPrivateKey_fp', 'ECPKParameters_print', 'PEM_read_bio_RSAPrivateKey', 
                'EC_GROUP_set_seed', 'DSA_get_default_method', 'RSA_meth_get0_app_data', 'ECDSA_verify', 'RSA_PSS_PARAMS_new', 'EC_KEY_get0_engine', 'DSA_do_verify', 'DSA_meth_get_sign_setup', 'ECDSA_do_sign', 'ENGINE_get_default_RSA', 'DH_set_method', 'DSA_clear_flags', 'EC_KEY_get_ex_data', 
                'RSA_get0_pss_params', 'DSA_get_method', 'DH_compute_key', 'RSA_get0_dmp1', 'EVP_PKEY_get0_DH', 'DSA_meth_dup', 'DH_meth_free', 'EC_KEY_get_method', 'RSA_get0_dmq1', 'PEM_write_bio_EC_PUBKEY', 'EC_POINT_get_affine_coordinates', 'RSA_private_encrypt', 'RSA_get_method', 'RSA_check_key_ex', 
                'RSA_OAEP_PARAMS_free', 'DSA_meth_set_init', 'DIRECTORYSTRING_new', 'PEM_write_bio_ECPKParameters', 'EC_KEY_set_ex_data', 'DSA_up_ref', 'RSA_blinding_on', 'd2i_ECDSA_SIG', 'RSA_PKCS1_OpenSSL', 'EC_KEY_clear_flags', 'EC_GROUP_new_curve_GFp', 'd2i_DSAPrivateKey_bio', 'RSA_meth_set_init', 
                'DSA_meth_set_sign_setup', 'EC_GFp_nist_method', 'RSA_padding_add_X931', 'PEM_read_bio_RSA_PUBKEY', 'RSA_OAEP_PARAMS_new', 'DH_new_by_nid', 'DSA_meth_set1_name', 'EC_GROUP_get0_order', 'DH_meth_get_compute_key', 'ENGINE_get_DH', 'PEM_read_bio_DSAPrivateKey', 'DH_new', 'PEM_write_DSAparams', 
                'EC_GROUP_get_ecpkparameters', 'ENGINE_set_default_RSA', 'd2i_ECPrivateKey_fp', 'ENGINE_get_EC', 'DSA_dup_DH', 'PEM_write_RSAPrivateKey', 'd2i_RSAPrivateKey_bio', 'DH_set0_pqg', 'EC_GFp_mont_method', 'DH_KDF_X9_42', 'EC_POINTs_make_affine', 'DH_bits', 'RSA_padding_check_PKCS1_OAEP', 
                'EC_KEY_dup', 'PEM_write_DHparams', 'BN_RECP_CTX_free', 'EVP_PKEY_get0_RSA', 'i2d_DSA_PUBKEY_bio', 'DH_meth_get_bn_mod_exp', 'd2i_EC_PUBKEY_fp', 'EC_GROUP_get_curve_GF2m', 'RSA_meth_set_flags', 'DSA_sign_setup', 'EC_POINT_make_affine', 'EC_GROUP_new_curve_GF2m', 'RSA_padding_add_PKCS1_PSS_mgf1', 
                'EC_GROUP_get_curve_GFp', 'd2i_DSA_PUBKEY', 'i2d_RSA_PUBKEY_bio', 'EC_KEY_METHOD_get_keygen', 'd2i_DSAPublicKey', 'EC_POINTs_mul', 'ENGINE_register_DSA', 'DH_meth_set_finish', 'EC_KEY_set_enc_flags', 'EC_KEY_set_public_key_affine_coordinates', 'RSA_meth_new', 'EVP_PKEY_set1_DSA', 
                'i2d_ECPrivateKey_fp', 'RSA_pkey_ctx_ctrl', 'd2i_RSA_OAEP_PARAMS', 'EVP_PKEY_get1_EC_KEY', 'BN_RECP_CTX_new', 'PEM_write_bio_RSAPublicKey', 'd2i_DIRECTORYSTRING', 'EC_POINT_is_at_infinity', 'EC_KEY_copy', 'EC_POINT_dbl', 'DSA_print', 'EC_KEY_free', 'ECDH_KDF_X9_62', 'PEM_write_DSAPrivateKey', 
                'DH_meth_set_bn_mod_exp', 'DSA_new_method', 'DSA_generate_parameters_ex', 'PEM_read_ECPrivateKey', 'EC_KEY_set_flags', 'EC_GROUP_set_curve_GF2m', 'ENGINE_unregister_DSA', 'RSA_padding_check_none', 'DH_size', 'RSA_check_key', 'RSA_get_default_method', 'EC_KEY_new_method', 'RSA_verify_ASN1_OCTET_STRING', 
                'DH_get_ex_data', 'EC_GROUP_get0_generator', 'DSA_free', 'DSA_SIG_free', 'RSA_new_method', 'ECParameters_print_fp', 'PEM_read_DHparams', 'EC_KEY_METHOD_get_init', 'ERR_load_DSA_strings', 'd2i_ECPrivateKey', 'EC_KEY_new_by_curve_name', 'RSA_padding_add_SSLv23', 'DSA_set0_pqg', 'ECPKPARAMETERS_new', 
                'i2d_ECDSA_SIG', 'EC_POINT_point2oct', 'RSA_sign', 'RSA_padding_check_SSLv23', 'DH_get0_key', 'RSA_get0_engine', 'i2d_DIRECTORYSTRING', 'EC_KEY_get_flags', 'd2i_DSA_PUBKEY_bio', 'ENGINE_register_DH', 'EC_KEY_get_default_method', 'RSA_meth_get_keygen', 'DH_set_ex_data', 'DH_meth_get_finish', 
                'RSA_generate_multi_prime_key', 'ENGINE_register_EC', 'RSA_blinding_off', 'DSA_OpenSSL', 'EC_POINT_get_affine_coordinates_GF2m', 'DSA_meth_set_keygen', 'EC_GROUP_get_ecparameters', 'DH_check_pub_key', 'DSA_print_fp', 'DH_check', 'd2i_RSA_PUBKEY_bio']

openssl11 = {
    'libname': 'openSSL1.1',
    #'APIs': ['AES_encrypt', 'AES_decrypt', 'RSA_sign', 'RSA_verify'],
    'APIs': openssl11_APIs,
    'elfname': 'libcrypto.so.1.1*'
}


#openssl3_APIs = list_dynsym("/home/oak/Git/PQDetector/pqscan/openssl-3.3.1/libcrypto.so", ["PKEY"])
#pprint.pp(openssl3_APIs, indent=4)

openssl3_APIs = ['EVP_PKEY_get_int_param',
    'EVP_PKEY_add1_attr_by_OBJ',
    'EVP_PKEY_get1_encoded_public_key',
    'EVP_PKEY_new',
    'EVP_PKEY_verify_recover_init',
    'EVP_PKEY_CTX_get_cb',
    'EVP_PKEY_CTX_set1_tls1_prf_secret',
    'EVP_PKEY_asn1_set_item',
    'EVP_PKEY_CTX_get_group_name',
    'EVP_PKEY_meth_get_decrypt',
    'EVP_PKEY_decapsulate',
    'EVP_PKEY_set_type',
    'EVP_PKEY_meth_find',
    'EVP_PKEY_CTX_set_rsa_pss_saltlen',
    'EVP_PKEY_meth_set_ctrl',
    'EVP_PKEY_save_parameters',
    'EVP_PKEY_set1_engine',
    'EVP_PKEY_CTX_free',
    'EVP_PKEY_CTX_set0_dh_kdf_ukm',
    'EVP_PKEY_meth_set_decrypt',
    'EVP_PKEY_new_raw_public_key_ex',
    'X509_PKEY_new',
    'EVP_PKEY_get_security_bits',
    'EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md_name',
    'EVP_PKEY_meth_get0_info',
    'EVP_PKEY_meth_get_digestverify',
    'EVP_PKEY_set_type_by_keymgmt',
    'EVP_PKEY_CTX_set_group_name',
    'EVP_PKEY_get_ex_data',
    'EVP_PKEY_CTX_set_dh_paramgen_gindex',
    'EVP_PKEY_missing_parameters',
    'EVP_PKEY_meth_get_param_check',
    'EVP_PKEY_CTX_add1_hkdf_info',
    'EVP_PKEY_meth_set_verifyctx',
    'EVP_PKEY_CTX_set1_hkdf_key',
    'EVP_PKEY_get_params',
    'EVP_PKEY_asn1_get0',
    'EVP_PKEY_asn1_add0',
    'EVP_PKEY_CTX_get0_peerkey',
    'EVP_PKEY_CTX_get0_libctx',
    'EVP_PKEY_get0_DSA',
    'EVP_PKEY_verify_init_ex',
    'EVP_PKEY_CTX_set_dh_pad',
    'EVP_PKEY_set_ex_data',
    'EVP_PKEY_cmp',
    'EVP_PKEY_verify_init',
    'EVP_PKEY_CTX_set_params',
    'EVP_PKEY_auth_decapsulate_init',
    'EVP_PKEY_sign_init',
    'EVP_PKEY_CTX_set_dh_paramgen_type',
    'EVP_PKEY_get_raw_public_key',
    'EVP_PKEY_asn1_set_security_bits',
    'EVP_PKEY_asn1_find_str',
    'EVP_PKEY_meth_set_keygen',
    'EVP_PKEY_meth_get_derive',
    'EVP_PKEY_new_mac_key',
    'EVP_PKEY_get1_RSA',
    'EVP_PKEY_encapsulate_init',
    'EVP_PKEY_get0',
    'EVP_PKEY_meth_set_param_check',
    'PKEY_USAGE_PERIOD_new',
    'EVP_PKEY_asn1_set_free',
    'EVP_PKEY_CTX_new_id',
    'EVP_PKEY_meth_get_digest_custom',
    'EVP_PKEY_CTX_set_ecdh_cofactor_mode',
    'EVP_PKEY_CTX_get0_pkey',
    'EVP_PKEY_CTX_set_rsa_pss_keygen_md_name',
    'EVP_PKEY_CTX_get0_propq',
    'EVP_PKEY_CTX_set_ecdh_kdf_type',
    'EVP_PKEY_meth_get_verify_recover',
    'EVP_PKEY_CTX_get_keygen_info',
    'EVP_PKEY_asn1_set_get_pub_key',
    'EVP_PKEY_CTX_get_rsa_padding',
    'EVP_PKEY_sign_init_ex',
    'EVP_PKEY_print_params',
    'EVP_PKEY_print_public',
    'EVP_PKEY_meth_remove',
    'i2d_PKEY_USAGE_PERIOD',
    'EVP_PKEY_new_raw_private_key',
    'EVP_PKEY_get0_poly1305',
    'EVP_PKEY_get_bn_param',
    'EVP_PKEY_meth_get_digestsign',
    'EVP_PKEY_CTX_get_ecdh_cofactor_mode',
    'EVP_PKEY_asn1_set_set_pub_key',
    'EVP_PKEY_meth_get_copy',
    'EVP_PKEY_CTX_set_rsa_pss_keygen_saltlen',
    'EVP_PKEY_is_a',
    'EVP_PKEY_get_id',
    'EVP_PKEY_CTX_set_ecdh_kdf_outlen',
    'EVP_PKEY_add1_attr_by_txt',
    'EVP_PKEY_CTX_get_operation',
    'EVP_PKEY_CTX_dup',
    'EVP_PKEY_paramgen',
    'EVP_PKEY_CTX_get_rsa_oaep_md_name',
    'EVP_PKEY_CTX_set1_id',
    'EVP_PKEY_meth_get_signctx',
    'EVP_PKEY_CTX_set_dh_kdf_outlen',
    'EVP_PKEY_CTX_get_signature_md',
    'EVP_PKEY_meth_set_digestsign',
    'EVP_PKEY_CTX_set_dsa_paramgen_md_props',
    'EVP_PKEY_meth_set_sign',
    'EVP_PKEY_get0_description',
    'EVP_PKEY_get_field_type',
    'EVP_PKEY_asn1_set_siginf',
    'EVP_PKEY_fromdata_settable',
    'EVP_PKEY_CTX_set_rsa_oaep_md_name',
    'OSSL_STORE_INFO_get0_PKEY',
    'EVP_PKEY_meth_set_digestverify',
    'EVP_PKEY_paramgen_init',
    'EVP_PKEY_CTX_set_data',
    'EVP_PKEY_get_ec_point_conv_form',
    'EVP_PKEY_gettable_params',
    'EVP_PKEY_CTX_set_kem_op',
    'EVP_PKEY_up_ref',
    'EVP_PKEY_CTX_get1_id_len',
    'EVP_PKEY_assign',
    'EVP_PKEY_decapsulate_init',
    'EVP_PKEY_meth_set_verify',
    'EVP_PKEY_meth_set_signctx',
    'EVP_PKEY_generate',
    'EVP_PKEY_meth_copy',
    'EVP_PKEY_sign',
    'EVP_PKEY_meth_free',
    'EVP_PKEY_meth_set_paramgen',
    'EVP_PKEY_CTX_set_ec_param_enc',
    'EVP_PKEY_meth_set_check',
    'EVP_PKEY_asn1_find',
    'EVP_PKEY_meth_get_paramgen',
    'EVP_PKEY_CTX_get0_dh_kdf_oid',
    'EVP_PKEY_set_type_str',
    'EVP_PKEY_get_raw_private_key',
    'EVP_PKEY_get_attr_count',
    'EVP_PKEY_copy_parameters',
    'EVP_PKEY_set1_EC_KEY',
    'EVP_PKEY_add1_attr',
    'EVP_PKEY_keygen',
    'EVP_PKEY_param_check_quick',
    'EVP_PKEY_encrypt_old',
    'EVP_PKEY_CTX_ctrl',
    'EVP_PKEY_type_names_do_all',
    'EVP_PKEY_get_group_name',
    'EVP_PKEY_fromdata',
    'EVP_PKEY_get_default_digest_name',
    'EVP_PKEY_get0_EC_KEY',
    'EVP_PKEY_CTX_get_ecdh_kdf_type',
    'EVP_PKEY_settable_params',
    'EVP_PKEY_cmp_parameters',
    'EVP_PKEY_CTX_set_dsa_paramgen_q_bits',
    'EVP_PKEY_CTX_set_dhx_rfc5114',
    'EVP_PKEY_asn1_set_public',
    'EVP_PKEY_type',
    'EVP_PKEY_CTX_set_mac_key',
    'EVP_PKEY_get1_DSA',
    'EVP_PKEY_get0_hmac',
    'EVP_PKEY_CTX_hex2ctrl',
    'EVP_PKEY_CTX_set0_dh_kdf_oid',
    'EVP_PKEY_meth_set_encrypt',
    'EVP_PKEY_meth_get_public_check',
    'EVP_PKEY_CTX_set_rsa_keygen_pubexp',
    'EVP_PKEY_verify_recover_init_ex',
    'EVP_PKEY_decrypt_init_ex',
    'EVP_PKEY_CTX_get_ecdh_kdf_md',
    'EVP_PKEY_dup',
    'EVP_PKEY_check',
    'EVP_PKEY_CTX_set0_ecdh_kdf_ukm',
    'EVP_PKEY_print_private_fp',
    'EVP_PKCS82PKEY_ex',
    'EVP_PKEY_CTX_get_dh_kdf_outlen',
    'EVP_PKEY_set_utf8_string_param',
    'EVP_PKEY_export',
    'EVP_PKEY_CTX_get0_provider',
    'EVP_PKEY_get0_engine',
    'EVP_PKEY_get_attr_by_NID',
    'EVP_PKEY_asn1_set_ctrl',
    'EVP_PKEY_get_base_id',
    'EVP_PKEY_meth_get_cleanup',
    'EVP_PKEY_get1_DH',
    'EVP_PKEY_CTX_set1_rsa_keygen_pubexp',
    'EVP_PKEY_CTX_set_dh_paramgen_prime_len',
    'EVP_PKEY_CTX_set_rsa_pss_keygen_md',
    'EVP_PKEY_encrypt_init_ex',
    'EVP_PKEY_meth_get_init',
    'EVP_PKEY_CTX_set_ecdh_kdf_md',
    'EVP_PKEY_meth_set_digest_custom',
    'EVP_PKEY_new_raw_private_key_ex',
    'EVP_PKEY_asn1_set_check',
    'EVP_PKEY_CTX_set_signature_md',
    'EVP_PKEY_get_bits',
    'EVP_PKEY_CTX_set_hkdf_mode',
    'EVP_PKEY_get_utf8_string_param',
    'EVP_PKEY_private_check',
    'EVP_PKEY_meth_get_count',
    'EVP_PKEY_Q_keygen',
    'EVP_PKEY_verify',
    'EVP_PKEY_CTX_set_cb',
    'EVP_PKEY_meth_set_cleanup',
    'EVP_PKEY_set_params',
    'EVP_PKEY_CTX_get1_id',
    'EVP_PKEY_CTX_is_a',
    'EVP_PKEY_print_private',
    'EVP_PKEY_CTX_set_dsa_paramgen_seed',
    'EVP_PKEY_encapsulate',
    'EVP_PKEY_CTX_set_dh_kdf_type',
    'EVP_PKEY_set_int_param',
    'EVP_PKEY_meth_get_ctrl',
    'EVP_PKEY_CTX_get_rsa_oaep_md',
    'EVP_PKEY_eq',
    'EVP_PKEY_set1_RSA',
    'EVP_PKEY_print_params_fp',
    'EVP_PKEY_public_check_quick',
    'EVP_PKEY_CTX_set1_hkdf_salt',
    'EVP_PKEY_CTX_ctrl_uint64',
    'EVP_PKEY_CTX_set_scrypt_N',
    'EVP_PKEY_meth_set_derive',
    'EVP_PKEY_CTX_set_scrypt_maxmem_bytes',
    'EVP_PKEY_CTX_set_scrypt_p',
    'EVP_PKEY_CTX_set_scrypt_r',
    'EVP_PKEY_CTX_ctrl_str',
    'EVP_PKEY_get_default_digest_nid',
    'EVP_PKEY_CTX_set_tls1_prf_md',
    'EVP_PKEY_get0_siphash',
    'EVP_PKEY_CTX_set_dsa_paramgen_md',
    'EVP_PKEY_get_size',
    'EVP_PKEY_pairwise_check',
    'EVP_PKEY_decrypt_init',
    'EVP_PKEY_set_bn_param',
    'EVP_PKEY_derive_set_peer_ex',
    'EVP_PKEY_set_size_t_param',
    'EVP_PKEY_encrypt',
    'EVP_PKEY_CTX_set_dh_nid',
    'EVP_PKEY_set_octet_string_param',
    'EVP_PKEY_CTX_get0_rsa_oaep_label',
    'EVP_PKEY_CTX_set0_keygen_info',
    'EVP_PKEY_CTX_set_dh_paramgen_generator',
    'EVP_PKEY_new_CMAC_key',
    'EVP_PKEY_CTX_get_params',
    'EVP_PKEY_get0_type_name',
    'EVP_PKEY_CTX_set_rsa_oaep_md',
    'EVP_PKEY_can_sign',
    'EVP_PKEY_set1_DH',
    'EVP_PKEY_CTX_get0_ecdh_kdf_ukm',
    'EVP_PKEY_asn1_copy',
    'EVP_PKEY_public_check',
    'EVP_PKEY_asn1_free',
    'EVP_PKEY_CTX_get_ecdh_kdf_outlen',
    'EVP_PKEY_meth_get_keygen',
    'EVP_PKEY_CTX_get_rsa_mgf1_md_name',
    'EVP_PKEY_decrypt',
    'EVP_PKEY_print_public_fp',
    'EVP_PKEY_meth_set_copy',
    'EVP_PKEY_get_octet_string_param',
    'EVP_PKEY_CTX_md',
    'EVP_PKEY_get_attr',
    'EVP_PKEY_meth_set_public_check',
    'EVP_PKEY_CTX_set1_scrypt_salt',
    'EVP_PKEY_CTX_set_rsa_mgf1_md_name',
    'EVP_PKEY_get_attr_by_OBJ',
    'EVP_PKEY_CTX_set_dsa_paramgen_bits',
    'EVP_PKEY_derive_set_peer',
    'EVP_PKEY_encrypt_init',
    'X509_PKEY_free',
    'EVP_PKEY_set1_encoded_public_key',
    'EVP_PKEY_verify_recover',
    'EVP_PKEY_CTX_set_rsa_pss_keygen_mgf1_md',
    'EVP_PKEY_free',
    'EVP_PKEY_CTX_set_dh_rfc5114',
    'EVP_PKEY_asn1_get_count',
    'EVP_PKEY_get0_DH',
    'EVP_PKEY_get0_asn1',
    'EVP_PKEY_CTX_set_dsa_paramgen_type',
    'EVP_PKEY_asn1_new',
    'EVP_PKEY_meth_get0',
    'PKEY_USAGE_PERIOD_free',
    'EVP_PKEY_meth_add0',
    'EVP_PKEY_asn1_set_param',
    'EVP_PKEY_CTX_set1_pbe_pass',
    'EVP_PKEY_CTX_set_ec_paramgen_curve_nid',
    'EVP_PKEY_CTX_get_dh_kdf_md',
    'EVP_PKEY_meth_set_verify_recover',
    'EVP_PKEY_add1_attr_by_NID',
    'EVP_PKEY_asn1_set_private',
    'EVP_PKEY_asn1_set_set_priv_key',
    'd2i_PKEY_USAGE_PERIOD',
    'EVP_PKEY_CTX_new_from_name',
    'EVP_PKEY_CTX_get_rsa_mgf1_md',
    'EVP_PKEY_asn1_set_public_check',
    'EVP_PKEY_asn1_set_get_priv_key',
    'EVP_PKEY_CTX_set0_rsa_oaep_label',
    'EVP_PKEY_decrypt_old',
    'EVP_PKEY_CTX_new',
    'EVP_PKEY_CTX_str2ctrl',
    'EVP_PKEY_asn1_get0_info',
    'EVP_PKEY_asn1_set_param_check',
    'EVP_PKEY_asn1_add_alias',
    'EVP_PKEY_CTX_add1_tls1_prf_seed',
    'EVP_PKEY_meth_new',
    'EVP_PKEY_CTX_set_rsa_keygen_primes',
    'EVP_PKEY_get0_RSA',
    'EVP_PKEY_param_check',
    'EVP_PKEY_meth_get_check',
    'EVP_PKEY_CTX_set_rsa_padding',
    'EVP_PKEY_parameters_eq',
    'EVP_PKEY_derive',
    'EVP_PKEY_CTX_set_dh_paramgen_subprime_len',
    'EVP_PKEY_CTX_gettable_params',
    'EVP_PKEY_CTX_set_rsa_keygen_bits',
    'EVP_PKEY_CTX_set_hkdf_md',
    'EVP_PKEY_meth_get_sign',
    'EVP_PKEY_new_raw_public_key',
    'EVP_PKEY_CTX_set_rsa_mgf1_md',
    'OSSL_STORE_INFO_get1_PKEY',
    'EVP_PKEY_meth_get_verify',
    'EVP_PKEY_get0_provider',
    'EVP_PKCS82PKEY',
    'PKEY_USAGE_PERIOD_it',
    'EVP_PKEY_CTX_get_data',
    'EVP_PKEY_set1_DSA',
    'EVP_PKEY_CTX_get_rsa_pss_saltlen',
    'EVP_PKEY_derive_init_ex',
    'EVP_PKEY_get1_EC_KEY',
    'EVP_PKEY_digestsign_supports_digest',
    'EVP_PKEY_todata',
    'EVP_PKEY_CTX_set_dsa_paramgen_gindex',
    'EVP_PKEY_fromdata_init',
    'EVP_PKEY_CTX_new_from_pkey',
    'OSSL_STORE_INFO_new_PKEY',
    'EVP_PKEY_CTX_settable_params',
    'EVP_PKEY_meth_get_verifyctx',
    'EVP_PKEY_derive_init',
    'EVP_PKEY_keygen_init',
    'EVP_PKEY_CTX_set_app_data',
    'EVP_PKEY_CTX_set_dh_kdf_md',
    'EVP_PKEY2PKCS8',
    'EVP_PKEY_CTX_get_dh_kdf_type',
    'EVP_PKEY_get_size_t_param',
    'EVP_PKEY_CTX_get_app_data',
    'EVP_PKEY_meth_get_encrypt',
    'EVP_PKEY_auth_encapsulate_init',
    'EVP_PKEY_delete_attr',
    'EVP_PKEY_CTX_set_dh_paramgen_seed',
    'EVP_PKEY_meth_set_init',
    'EVP_PKEY_CTX_get0_dh_kdf_ukm'
]


openssl3 = {
    'libname': 'openSSL3.x',
    'APIs': openssl3_APIs,
    'elfname': 'libcrypto.so.3*'

}

wolfssl_APIs = ['wc_ecc_set_curve',
    'wc_RsaUnPad_ex',
    'wc_RsaKeyToDer',
    'wc_ecc_key_free',
    'wc_ecc_gen_k',
    'wc_ecc_shared_secret',
    'wc_RsaPrivateDecryptInline',
    'wc_ecc_is_point',
    'wc_ecc_del_point_h',
    'wc_ecc_make_key',
    'wc_DhCheckKeyPair',
    'wc_ecc_export_point_der_ex',
    'wc_ecc_import_raw',
    'wc_RsaPublicKeyDecode_ex',
    'wc_DhCheckPubKey',
    'wc_RsaSSL_VerifyInline',
    'wc_RsaPublicKeyDecode',
    'wc_ecc_export_private_only',
    'wc_RsaSSL_Verify_ex2',
    'wc_DhParamsLoad',
    'wc_ecc_size',
    'wc_RsaKeyToPublicDer',
    'wc_ecc_import_private_key',
    'wc_ecc_verify_hash_ex',
    'wc_DhExportParamsRaw',
    'wc_RsaPSS_VerifyInline',
    'wc_RsaPSS_CheckPadding_ex2',
    'wc_ecc_sign_hash',
    'wc_RsaExportKey',
    'wc_ecc_get_curve_id_from_oid',
    'wc_RsaPrivateDecryptInline_ex',
    'wc_DhCheckPrivKey_ex',
    'wc_RsaPad_ex',
    'wc_ecc_get_curve_size_from_id',
    'wc_RsaPrivateKeyValidate',
    'wc_ecc_import_unsigned',
    'wc_ecc_copy_point',
    'wc_RsaPSS_CheckPadding',
    'wc_RsaFunction',
    'wc_ecc_export_ex',
    'wc_ecc_sig_to_rs',
    'wc_ecc_export_x963',
    'wc_RsaPSS_VerifyCheckInline',
    'wc_DhGetNamedKeyParamSize',
    'wc_ecc_make_key_ex2',
    'wc_RsaPublicEncrypt',
    'wc_ecc_is_valid_idx',
    'wc_RsaSSL_Verify',
    'wc_DhAgree',
    'wc_ecc_shared_secret_ex',
    'wc_ecc_get_curve_idx',
    'wc_ecc_new_point',
    'wc_ecc_make_pub',
    'wc_ecc_set_flags',
    'wc_DhSetKey',
    'wc_RsaPrivateDecrypt_ex',
    'wc_ecc_get_name',
    'wc_DhCheckPubKey_ex',
    'wc_ecc_export_private_raw',
    'wc_ecc_key_new',
    'wc_DhSetCheckKey',
    'wc_RsaPublicEncrypt_ex',
    'wc_RsaEncryptSize',
    'wc_ecc_forcezero_point',
    'wc_ecc_import_x963_ex',
    'wc_ecc_sig_size',
    'wc_ecc_get_curve_size_from_name',
    'wc_ecc_get_curve_id',
    'wc_RsaSSL_Verify_ex',
    'wc_ecc_sig_size_calc',
    'wc_ecc_rs_to_sig',
    'wc_RsaPublicKeyDecodeRaw',
    'wc_RsaPSS_Sign',
    'wc_RsaPublicKeyDerSize',
    'wc_ecc_export_point_der',
    'wc_ecc_del_point',
    'wc_ecc_import_point_der',
    'wc_DhSetKey_ex',
    'wc_DhCopyNamedKey',
    'wc_ecc_export_public_raw',
    'wc_DhGenerateKeyPair',
    'wc_RsaPSS_VerifyInline_ex',
    'wc_ecc_import_private_key_ex',
    'wc_ecc_check_key',
    'wc_DhKeyDecode',
    'wc_RsaPSS_VerifyCheck',
    'wc_RsaPSS_Verify',
    'wc_ecc_get_curve_params',
    'wc_RsaPrivateKeyDecodeRaw',
    'wc_RsaPrivateDecrypt',
    'wc_ecc_get_oid',
    'wc_DhGenerateParams',
    'wc_ecc_point_is_at_infinity',
    'wc_ecc_init_ex',
    'wc_ecc_init',
    'wc_DhGetNamedKeyMinSize',
    'wc_ecc_mulmod',
    'wc_DhCheckPubValue',
    'wc_ecc_verify_hash',
    'wc_RsaKeyToPublicDer_ex',
    'wc_Dh_ffdhe2048_Get',
    'wc_ecc_get_curve_id_from_dp_params',
    'wc_RsaSSL_Sign',
    'wc_ecc_export_x963_ex',
    'wc_ecc_make_pub_ex',
    'wc_RsaSetRNG',
    'wc_ecc_import_point_der_ex',
    'wc_DhSetNamedKey',
    'wc_RsaPSS_Sign_ex',
    'wc_ecc_import_x963',
    'wc_ecc_sign_hash_ex',
    'wc_DhCmpNamedKey',
    'wc_RsaPSS_CheckPadding_ex',
    'wc_ecc_make_key_ex',
    'wc_RsaFlattenPublicKey',
    'wc_ecc_get_curve_id_from_params',
    'wc_ecc_free',
    'wc_ecc_new_point_h',
    'wc_RsaPSS_Verify_ex',
    'wc_ecc_rs_raw_to_sig',
    'wc_RsaPrivateKeyDecode',
    'wc_ecc_import_raw_ex',
    'wc_DhCheckPrivKey',
    'wc_ecc_set_rng',
    'wc_ecc_cmp_point',
    'wc_ecc_get_curve_idx_from_name',
    'wc_ecc_get_curve_id_from_name'
]




wolfssl = {
    'libname': 'wolfSSL',
    'APIs': wolfssl_APIs,
    'elfname': 'libwolfssl*'
}



#mbedtls_APIs = list_dynsym("/home/oak/Git/PQDetector/pqscan/mbedtls/build/library/libmbedcrypto.so", ["mbedtls_dhm", "mbedtls_ecdsa", "mbedtls_rsa"])
#pprint.pp(mbedtls_APIs, indent=4)

mbedtls_APIs = ['mbedtls_rsa_rsassa_pss_verify',
    'mbedtls_rsa_export',
    'mbedtls_rsa_rsassa_pss_sign',
    'mbedtls_rsa_import',
    'mbedtls_rsa_rsaes_oaep_decrypt',
    'mbedtls_rsa_deduce_primes',
    'mbedtls_rsa_set_padding',
    'mbedtls_rsa_export_raw',
    'mbedtls_rsa_import_raw',
    'mbedtls_rsa_free',
    'mbedtls_rsa_rsassa_pss_sign_ext',
    'mbedtls_dhm_self_test',
    'mbedtls_rsa_pkcs1_decrypt',
    'mbedtls_dhm_set_group',
    'mbedtls_rsa_self_test',
    'mbedtls_rsa_gen_key',
    'mbedtls_ecdsa_sign_det_ext',
    'mbedtls_dhm_init',
    'mbedtls_ecdsa_genkey',
    'mbedtls_ecdsa_write_signature',
    'mbedtls_rsa_deduce_crt',
    'mbedtls_rsa_check_pubkey',
    'mbedtls_ecdsa_write_signature_det',
    'mbedtls_dhm_calc_secret',
    'mbedtls_dhm_parse_dhm',
    'mbedtls_rsa_rsassa_pkcs1_v15_verify',
    'mbedtls_rsa_rsaes_pkcs1_v15_encrypt',
    'mbedtls_rsa_pkcs1_verify',
    'mbedtls_rsa_deduce_private_exponent',
    'mbedtls_dhm_free',
    'mbedtls_ecdsa_sign_det',
    'mbedtls_dhm_make_public',
    'mbedtls_dhm_read_public',
    'mbedtls_rsa_rsassa_pkcs1_v15_sign',
    'mbedtls_rsa_pkcs1_encrypt',
    'mbedtls_ecdsa_can_do',
    'mbedtls_rsa_private',
    'mbedtls_ecdsa_init',
    'mbedtls_rsa_rsaes_oaep_encrypt',
    'mbedtls_dhm_make_params',
    'mbedtls_rsa_copy',
    'mbedtls_dhm_read_params',
    'mbedtls_ecdsa_write_signature_restartable',
    'mbedtls_ecdsa_read_signature_restartable',
    'mbedtls_ecdsa_verify',
    'mbedtls_ecdsa_read_signature',
    'mbedtls_ecdsa_free',
    'mbedtls_rsa_validate_crt',
    'mbedtls_ecdsa_sign',
    'mbedtls_rsa_complete',
    'mbedtls_rsa_export_crt',
    'mbedtls_rsa_get_len',
    'mbedtls_rsa_check_privkey',
    'mbedtls_rsa_public',
    'mbedtls_dhm_parse_dhmfile',
    'mbedtls_rsa_rsassa_pss_verify_ext',
    'mbedtls_rsa_pkcs1_sign',
    'mbedtls_ecdsa_from_keypair',
    'mbedtls_rsa_rsaes_pkcs1_v15_decrypt',
    'mbedtls_rsa_check_pub_priv',
    'mbedtls_rsa_init',
    'mbedtls_rsa_validate_params'
]


mbedtls = {
    'libname': 'MbedTLS',
    'APIs': mbedtls_APIs,
    'elfname': 'libmbedcrypto*'
}

CRYPTO_LIB = [openssl11, openssl3, wolfssl, mbedtls]
#CRYPTO_LIB = [openssl3]

#print(openssl11_APIs)
